export const TAG_OPTIONS = [
  'Array',
  'String',
  'Hash Table',
  'Math',
  'Dynamic Programming',
  'Sorting',
  'Greedy',
  'Depth-First Search',
  'Binary Search',
  'Database',
  'Bit Manipulation',
  'Matrix',
  'Tree',
  'Breadth-First Search',
  'Two Pointers',
  'Prefix Sum',
  'Heap (Priority Queue)',
  'Simulation',
  'Counting',
  'Graph Theory',
  'Binary Tree',
  'Stack',
  'Sliding Window',
  'Enumeration',
  'Design',
  'Backtracking',
  'Union-Find',
  'Number Theory',
  'Linked List',
  'Ordered Set',
  'Segment Tree',
  'Monotonic Stack',
  'Divide and Conquer',
  'Trie',
  'Combinatorics',
  'Bitmask',
  'Queue',
  'Recursion',
  'Geometry',
  'Binary Indexed Tree',
  'Memoization',
  'Binary Search Tree',
  'Hash Function',
  'Topological Sort',
  'Shortest Path',
  'String Matching',
  'Rolling Hash',
  'Game Theory',
  'Interactive',
  'Data Stream',
  'Monotonic Queue',
  'Brainteaser',
  'Doubly-Linked List',
  'Merge Sort',
  'Randomized',
  'Counting Sort',
  'Iterator',
  'Concurrency',
  'Quickselect',
  'Suffix Array',
  'Sweep Line',
  'Probability and Statistics',
  'Minimum Spanning Tree',
  'Bucket Sort',
  'Shell',
  'Reservoir Sampling',
  'Eulerian Circuit',
  'Radix Sort',
  'Strongly Connected Component',
  'Rejection Sampling',
  'Biconnected Component',
];
