import type { Metadata } from 'next';
import { Poppins, Raleway, JetBrains_Mono, Space_Grotesk, Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { cn } from "@/lib/utils";

const montserratHeading = Montserrat({subsets:['latin'],variable:'--font-heading'});

const spaceGrotesk = Space_Grotesk({subsets:['latin'],variable:'--font-sans'});

const fontSerif = Raleway({
  subsets: ['latin'],
  variable: '--font-serif',
});

const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        suppressHydrationWarning
        lang='en'
        className={cn("antialiased", fontSerif.variable, fontMono.variable, "font-sans", spaceGrotesk.variable, montserratHeading.variable)}
      >
        <body className='min-h-screen flex space-y-4 flex-col overflow-x-hidden'>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <main className='flex-1 flex flex-col px-2 md:px-4'>
              {children}
            </main>
            <footer>Footer placeholder</footer>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
